version: "3.9"

services:
  api:
    build: .
    container_name: backend-go-api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - postgres
    networks:
      - mynet

  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet

volumes:
  postgres_data:

networks:
  mynet:
